[package]
name = "spam"
version = "0.1.2"
authors = ["theovesy"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "*"
clap = { version = "4.2.2", features = ["derive"] }
